version: "3.7"

services:

  server:
    build:
      context: .
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - MYSQL_HOST=blesta-db-1
      - MYSQL_USER=blesta
      - MYSQL_PASSWORD=blesta
      - MYSQL_DATABASE=blesta
    volumes:
      - blesta:/var/www/html/config
      - blesta-cache:/var/www/html/cache
      - blesta-uploads:/var/www/uploads
    depends_on:
      - db

  db:
    image: mariadb:11.4.3
    restart: always
    environment:
      - MARIADB_USER=blesta
      - MARIADB_PASSWORD=blesta
      - MARIADB_DATABASE=blesta
      - MARIADB_ROOT_PASSWORD=blesta
    volumes:
      - blesta-db:/var/lib/mysql

volumes:
  blesta:
    name: "blesta"
  blesta-cache:
    name: "blesta-cache"
  blesta-uploads:
    name: "blesta-uploads"
  blesta-db:
    name: "blesta-db"